//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestoranEntities : DbContext
    {
        public RestoranEntities()
            : base("name=RestoranEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<menu_dishes> menu_dishes { get; set; }
        public virtual DbSet<orders_dishes> orders_dishes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TbDishes> TbDishes { get; set; }
        public virtual DbSet<TbKlients> TbKlients { get; set; }
        public virtual DbSet<TbMenus> TbMenus { get; set; }
        public virtual DbSet<TbOrders> TbOrders { get; set; }
        public virtual DbSet<TbUsers> TbUsers { get; set; }
    }
}
